apiVersion: batch/v1
kind: Job
metadata:
  name: pod-annotationmatch
spec:
  parallelism: 1
  template:
    metadata:
      annotations:
        annotation/annotationmatch: boo
    spec:
      schedulerName: annotation-scheduler
      containers:
        - name: pod-state
          image: busybox
          command: ["sh", "-c", "sleep 10"]
      restartPolicy: Never
  backoffLimit: 4
